FROM python:3.9-slim

WORKDIR /app

RUN pip install --upgrade pip \
    && pip install pandas pyarrow sqlalchemy psycopg2-binary requests boto3

COPY ./pipeline/bid_predictor_live_data_single_file.py /app/

ENTRYPOINT ["python", "bid_predictor_live_data_single_file.py"]
