features:
  carrier_code:
    categorical: true
    include_in_model: false
  flight_number:
    categorical: true
    include_in_model: false
  flight_code:
    derived: true
    categorical: true
    include_in_model: false


  travel_date:
    include_in_model: false
  departure_timestamp:
    include_in_model: false
  current_timestamp:
    include_in_model: false
  days_before_departure:
    include_in_model: true
    derived: true

  seats_available:
    categorical: true
    include_in_model: true

  item_count:
    categorical: true
    include_in_model: true
  usd_base_amount:
    categorical: true
    include_in_model: true
  fare_class:
    categorical: true
    include_in_model: true
  offer_time:
    include_in_model: false
  multiplier_fare_class:
    include_in_model: true
  multiplier_loyalty:
    include_in_model: true
  multiplier_success_history:
    include_in_model: true
  multiplier_payment_type:
    include_in_model: true
  upgrade_type:
    categorical: true
    include_in_model: true

  snapshot_num:
    include_in_model: false

  usd_base_amount_25%:
    derived: true
    include_in_model: true
  usd_base_amount_50%:
    derived: true
    include_in_model: true
  usd_base_amount_75%:
    derived: true
    include_in_model: true
  usd_base_amount_max:
    derived: true
    include_in_model: true
  num_offers:
    derived: true
    categorical: true
    include_in_model: true

