features:
  carrier_code:
    categorical: true
    include_in_model: false
  flight_number:
    categorical: true
    include_in_model: false
  flight_code:
    derived: true
    categorical: true
    include_in_model: false


  travel_date:
    include_in_model: false
  departure_timestamp:
    include_in_model: false
  current_timestamp:
    include_in_model: false
  days_before_departure:
    categorical: true
    bins: 
      min: 0
      max: 5
      nsteps: 76
      # nsteps: 121
    include_in_model: false
    derived: true

  seats_available:
    categorical: true
    impute_median: true
    bins: 
      min: -1
      max: 30
      interval: 1
    include_in_model: true

  item_count:
    categorical: true
    outlier:
      max: 5
    include_in_model: true
  usd_base_amount:
    categorical: true
    bins: 
      min: 0
      max: 1700
      interval: 10
      # interval: 100
    include_in_model: true
  fare_class:
    categorical: true
    include_in_model: true
  offer_time:
    categorical: true
    bins: 
      min: 0
      max: 30
      interval: 1  
    include_in_model: false
  multiplier_fare_class:
    impute_value: 1.0
    include_in_model: false
  multiplier_loyalty:
    impute_value: 1.0
    include_in_model: false
  multiplier_success_history:
    impute_value: 1.0
    include_in_model: false
  multiplier_payment_type:
    impute_value: 1.0
    include_in_model: false
  upgrade_type:
    categorical: true
    include_in_model: false

  snapshot_num:
    include_in_model: false

  usd_base_amount_25%:
    derived: true
    include_in_model: true
  usd_base_amount_50%:
    derived: true
    include_in_model: true
  usd_base_amount_75%:
    derived: true
    include_in_model: true
  usd_base_amount_max:
    derived: true
    include_in_model: true
  num_offers:
    derived: true
    categorical: true
    outlier:
      max: 16
    include_in_model: true

