# config/features.yaml
all_features:
  - f_clicks
  - f_impressions
  - f_ctr
  - f_bid
  - f_region
  - f_device

pre_features:
  - f_clicks
  - f_impressions
  - f_ctr
  - f_region
  - f_device

cat_features:
  - f_region
  - f_device

# 👉 Edit only this list to experiment
active_features:
  - f_clicks
  - f_impressions
  - f_ctr
  - f_region
  - f_device
